services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: homestead 
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: marine-logistics
    volumes:
      - ./migrations/V1__create_bookings.sql:/docker-entrypoint-initdb.d/init-00.sql
    ports:
      - 5432:5432

  migrations:
    build:
      context: .
      dockerfile: migrations.Dockerfile
    depends_on:
      - postgres
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181